# Generated by Django 5.0.6 on 2024-05-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='Davlatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='davlat_image')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davlat', to='travel.categories')),
            ],
        ),
    ]
