# Generated by Django 5.0.6 on 2024-05-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davlatlar',
            name='price',
            field=models.IntegerField(),
        ),
    ]
