# Generated by Django 5.0.6 on 2024-05-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_davlatlar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davlatlar',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='davlat', to='travel.categories'),
        ),
    ]
