# Generated by Django 5.0.6 on 2024-05-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_davlatlar_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.ImageField(upload_to='')),
                ('destination', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='reys_image')),
                ('reys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rays', to='travel.reys')),
            ],
        ),
    ]
