# Generated by Django 5.0.6 on 2024-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_reys_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='price',
            field=models.IntegerField(),
        ),
    ]
