# Generated by Django 5.0.6 on 2024-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_country_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reys',
            name='image',
            field=models.ImageField(null=True, upload_to='reys'),
        ),
    ]
