# Generated by Django 5.0.6 on 2024-05-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_reys_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='reys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='travel.reys'),
        ),
    ]
